const $=s=>document.querySelector(s),key='ai-recruitment-demo-v1';
const seed={jobs:[{id:'frontend',client:'TechCorp',title:'Senior Frontend Developer',jd:'Tìm Senior Frontend Developer có 5+ năm kinh nghiệm React/TypeScript, có tư duy sản phẩm và giao tiếp tiếng Anh tốt.'},{id:'product',client:'VinGroup',title:'Product Manager',jd:'Tìm Product Manager có kinh nghiệm phát triển sản phẩm số và phối hợp đa phòng ban.'},{id:'data',client:'DataVize',title:'Data Engineer',jd:'Tìm Data Engineer có kinh nghiệm xây dựng pipeline dữ liệu và làm việc với cloud.'}],candidates:[{id:'hai',jobId:'frontend',name:'Nguyễn Văn Hải',role:'Lead Frontend Engineer',match:'Phù hợp',status:'Đang xem',initials:'NH',cv:'Senior Frontend Developer with more than 5 years of experience building scalable web applications. Proficient in React, TypeScript and Next.js. Experienced in design systems, performance optimisation and close product collaboration.'},{id:'linh',jobId:'frontend',name:'Trần Thị Linh',role:'Senior React Developer',match:'Cân nhắc',status:'Phỏng vấn',initials:'TL',cv:'Senior React Developer with experience in TypeScript, component libraries and collaborative product teams.'},{id:'minh',jobId:'frontend',name:'Phạm Quang Minh',role:'Frontend Developer',match:'Chưa đánh giá',status:'Mới',initials:'PQ',cv:'Frontend Developer with React, JavaScript and web performance experience.'}],currentJobId:'frontend'};
let data;try{data=JSON.parse(localStorage.getItem(key))}catch{}if(!data?.jobs)data=structuredClone(seed);data.settings??={name:'Admin',email:'admin@airecruit.com'};let currentCandidateId=null,translated=false,editing=false;const statuses=['Mới','Đang xem','Phỏng vấn','Đề nghị','Đã tuyển','Từ chối'];
const save=()=>{try{localStorage.setItem(key,JSON.stringify(data));return true}catch{return false}},job=()=>data.jobs.find(x=>x.id===data.currentJobId),candidate=()=>data.candidates.find(x=>x.id===currentCandidateId),esc=x=>{const e=document.createElement('i');e.textContent=x;return e.innerHTML},notice=m=>{const t=$('.toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)};
function go(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.go===id));scrollTo(0,0)}
function renderJobs(q=''){q=q.toLowerCase();const found=data.jobs.filter(x=>(x.title+x.client).toLowerCase().includes(q));$('#job-list').innerHTML=found.length?found.map(x=>{const cs=data.candidates.filter(c=>c.jobId===x.id),matches=cs.filter(c=>c.match==='Phù hợp').length;return `<article class="job-card" data-job="${x.id}"><span class="tag">${esc(x.client)}</span><h3>${esc(x.title)}</h3><p class="muted">Vị trí đang tuyển</p><footer><span>♙ ${cs.length} ứng viên</span><span class="match">✦ ${matches?matches+' Phù hợp':'Chưa đánh giá'}</span></footer></article>`}).join(''):'<div class="empty-state">Không tìm thấy Job phù hợp.</div>';document.querySelectorAll('[data-job]').forEach(x=>x.onclick=()=>{data.currentJobId=x.dataset.job;save();renderWorkspace();go('workspace')})}
function renderWorkspace(){const j=job(),cs=data.candidates.filter(x=>x.jobId===j.id);$('#workspace-client').textContent=j.client.toUpperCase()+' · ĐANG MỞ';$('#workspace-title').textContent=j.title;$('#workspace-summary').textContent=cs.length+' ứng viên trong Job này';$('#workspace-jd').textContent=j.jd;$('#candidate-list').innerHTML=cs.length?cs.map(c=>`<article class="candidate-row" data-candidate="${c.id}"><div><span class="avatar">${c.initials}</span><b>${esc(c.name)}</b><small>${esc(c.role)}</small></div><span class="match">✦ ${c.match}</span><span class="status">${c.status}</span><span class="arrow">›</span></article>`).join(''):'<div class="empty-state">Job này chưa có ứng viên. Thêm CV để bắt đầu sàng lọc.</div>';document.querySelectorAll('[data-candidate]').forEach(x=>x.onclick=()=>{currentCandidateId=x.dataset.candidate;translated=false;renderDetail();go('detail')})}
function cv(c,vi=false){return vi?`<h4>TÓM TẮT</h4><p>Bản dịch do AI hỗ trợ: ${esc(c.cv)}</p><h4>KINH NGHIỆM</h4><p><b>${esc(c.role)}</b><br>Hãy đối chiếu bản gốc khi cần.</p>`:`<h4>SUMMARY</h4><p>${esc(c.cv)}</p><h4>EXPERIENCE</h4><p><b>${esc(c.role)}</b><br>Thông tin CV trong bản demo.</p>`}
function renderDetail(){const c=candidate();$('#detail-name').textContent=c.name;$('#detail-role').textContent=c.role+' · '+job().title;$('#status-text').textContent=c.status;$('#match-title').textContent=c.match;const r=$('#match-result');r.className=c.match==='Chưa đánh giá'?'result empty':'result';r.innerHTML=c.match==='Chưa đánh giá'?'Chạy đánh giá để xem mức phù hợp, lý do chính và điểm cần lưu ý.':'<b>Điểm phù hợp chính</b><ul><li>Kinh nghiệm và kỹ năng có liên quan đến yêu cầu Job.</li><li>Có thể trao đổi sâu hơn trong vòng phỏng vấn.</li></ul><b>Điểm cần lưu ý</b><ul><li>AI chỉ đưa gợi ý; hãy kiểm tra lại CV.</li></ul>';$('#ai-match').textContent=c.match==='Chưa đánh giá'?'✦ Đánh giá với AI':'✦ Đánh giá lại';$('#cv-content').innerHTML=cv(c);$('#ai-note').hidden=true;$('#tabs button[data-tab="original"]').classList.add('selected');const translatedTab=$('#tabs button[data-tab="translated"]');translatedTab.classList.remove('selected');translatedTab.disabled=true}
function fillJob(){const j=job();$('#job-title').value=editing?j.title:'';$('#job-client').value=editing?j.client:'';$('#job-jd').value=editing?j.jd:''}
function renderSettings(){const settings=data.settings;$('#settings-name').value=settings.name;$('#settings-email').value=settings.email;$('#profile-name').innerHTML=`${esc(settings.name)}<br><small id="profile-email">${esc(settings.email)}</small>`}
document.addEventListener('click',e=>{const x=e.target.closest('[data-go]');if(!x)return;if(x.dataset.go==='create'){editing=false;fillJob()}if(x.dataset.go==='add')$('.form-card .eyebrow').textContent='THÊM VÀO '+job().title.toUpperCase();if(x.dataset.go==='settings')renderSettings();go(x.dataset.go)});$('#job-search').oninput=e=>renderJobs(e.target.value);$('#edit-job').onclick=()=>{editing=true;fillJob();go('create')};
$('#save-settings').onclick=()=>{const name=$('#settings-name').value.trim(),email=$('#settings-email').value.trim();if(!name||!email)return notice('Vui lòng nhập tên và email.');if(!email.includes('@'))return notice('Email chưa đúng định dạng.');data.settings={name,email};save();renderSettings();notice('Đã lưu cài đặt.')};
$('#save-job').onclick=()=>{const title=$('#job-title').value.trim(),client=$('#job-client').value.trim(),jd=$('#job-jd').value.trim();if(!title||!client||!jd)return notice('Vui lòng nhập tên vị trí, khách hàng và JD.');if(editing){Object.assign(job(),{title,client,jd});notice('Đã lưu thay đổi Job.')}else{const id='job-'+Date.now();data.jobs.unshift({id,title,client,jd});data.currentJobId=id;notice('Đã tạo Job. Bạn có thể thêm ứng viên ngay.')}save();renderJobs($('#job-search').value);renderWorkspace();go('workspace')};
$('#save-candidate').onclick=()=>{const name=$('#candidate-name').value.trim(),role=$('#candidate-role').value.trim(),cvText=$('#candidate-cv').value.trim();if(!name||!role||!cvText)return notice('Vui lòng nhập tên, vị trí và nội dung CV.');const c={id:'candidate-'+Date.now(),jobId:job().id,name,role,cv:cvText,match:'Chưa đánh giá',status:'Mới',initials:name.split(/\s+/).slice(-2).map(x=>x[0]).join('').toUpperCase()};data.candidates.unshift(c);currentCandidateId=c.id;save();renderJobs($('#job-search').value);renderWorkspace();renderDetail();notice('Đã thêm ứng viên vào Job.');go('detail')};
$('#ai-match').onclick=async()=>{const b=$('#ai-match'),c=candidate();if(!c.cv||!job().jd)return notice('Cần có JD và nội dung CV trước khi đánh giá.');b.disabled=true;b.textContent='✦ Đang đánh giá…';await new Promise(r=>setTimeout(r,800));c.match='Phù hợp';save();renderDetail();b.disabled=false;renderWorkspace();renderJobs($('#job-search').value);notice('Đã hoàn tất đánh giá AI. Đây là gợi ý hỗ trợ.')};
$('#translate').onclick=async()=>{const b=$('#translate');b.disabled=true;b.textContent='✦ Đang dịch…';await new Promise(r=>setTimeout(r,650));translated=true;const tab=$('#tabs button[data-tab="translated"]');tab.disabled=false;tab.click();b.textContent='✦ Dịch nhanh sang tiếng Việt';b.disabled=false;notice('Đã tạo bản dịch tiếng Việt.')};$('#tabs').onclick=e=>{const tab=e.target.dataset.tab;if(!tab||tab==='translated'&&!translated)return;document.querySelectorAll('#tabs button').forEach(x=>x.classList.toggle('selected',x===e.target));const vi=tab==='translated';$('#cv-content').innerHTML=cv(candidate(),vi);$('#ai-note').hidden=!vi};
$('#status-trigger').onclick=()=>{const m=$('#status-menu'),c=candidate();m.hidden=!m.hidden;m.innerHTML=statuses.map(s=>`<button data-status="${s}">${s===c.status?'✓ ':''}${s}</button>`).join('');m.querySelectorAll('button').forEach(x=>x.onclick=()=>{m.hidden=true;if(x.dataset.status===c.status)return;c.status=x.dataset.status;save();renderDetail();renderWorkspace();renderJobs($('#job-search').value);notice('Đã cập nhật trạng thái.')})};renderSettings();renderJobs();renderWorkspace();

// Supabase data layer: Jobs, Candidates and Applications are stored remotely.
var dbClient=window.supabase.createClient(window.SUPABASE_CONFIG.url,window.SUPABASE_CONFIG.publishableKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
var dbUser=null;
var dbStatus={Mới:'new','Đang xem':'reviewing','Phỏng vấn':'interview','Đề nghị':'offer','Đã tuyển':'hired','Từ chối':'rejected'};
var dbLabel=Object.fromEntries(Object.entries(dbStatus).map(([label,value])=>[value,label]));
var dbError=error=>notice(error?.message||'Không thể kết nối Supabase. Vui lòng thử lại.');
async function loadFromSupabase(){const [{data:jobRows,error:jobError},{data:appRows,error:appError}]=await Promise.all([dbClient.from('jobs').select('*').order('created_at',{ascending:false}),dbClient.from('applications').select('id,job_id,status,candidates(id,name,source,cv_text)').order('created_at',{ascending:false})]);if(jobError||appError){dbError(jobError||appError);return}data.jobs=(jobRows||[]).map(row=>({id:row.id,title:row.title,client:row.client_name,jd:row.jd_text}));data.candidates=(appRows||[]).map(row=>({id:row.candidates.id,applicationId:row.id,jobId:row.job_id,name:row.candidates.name,role:row.candidates.source||'Ứng viên',cv:row.candidates.cv_text||'',match:'Chưa đánh giá',status:dbLabel[row.status]||'Mới',initials:(row.candidates.name||'?').split(/\s+/).slice(-2).map(word=>word[0]).join('').toUpperCase()}));if(!data.jobs.some(item=>item.id===data.currentJobId))data.currentJobId=data.jobs[0]?.id||null;renderJobs();if(data.currentJobId)renderWorkspace();}
async function requireDbUser(){if(dbUser)return dbUser;const {data:{user}}=await dbClient.auth.getUser();dbUser=user;if(!dbUser){go('auth-login');notice('Vui lòng đăng nhập để lưu dữ liệu Supabase.')}return dbUser}
$('#sign-in').onclick=async()=>{const email=$('#auth-email').value.trim(),password=$('#auth-password').value;if(!email||!password)return $('#auth-message').textContent='Vui lòng nhập email và mật khẩu.';const {data:authData,error}=await dbClient.auth.signInWithPassword({email,password});if(error)return $('#auth-message').textContent=error.message;dbUser=authData.user;$('#auth-message').textContent='Đăng nhập thành công.';await loadFromSupabase();go('jobs')};
$('#sign-up').onclick=async()=>{const fullname=$('#reg-fullname').value.trim(),email=$('#reg-email').value.trim(),password=$('#reg-password').value;if(!fullname)return $('#reg-message').textContent='Vui lòng nhập họ và tên.';if(!email)return $('#reg-message').textContent='Vui lòng nhập email.';if(password.length<6)return $('#reg-message').textContent='Mật khẩu cần có ít nhất 6 ký tự.';const {data:authData,error}=await dbClient.auth.signUp({email,password,options:{data:{full_name:fullname}}});if(error)return $('#reg-message').textContent=error.message;if(!authData.session)return $('#reg-message').textContent='Hãy xác nhập email, sau đó quay lại đăng nhập.';dbUser=authData.user;await loadFromSupabase();go('jobs')};
$('#goto-register').onclick=()=>{$('#auth-message').textContent='';go('auth-register')};
$('#goto-login').onclick=()=>{$('#reg-message').textContent='';go('auth-login')};
$('#save-job').onclick=async()=>{const user=await requireDbUser();if(!user)return;const title=$('#job-title').value.trim(),client=$('#job-client').value.trim(),jd=$('#job-jd').value.trim();if(!title||!client||!jd)return notice('Vui lòng nhập tên vị trí, khách hàng và JD.');const payload={title,client_name:client,jd_text:jd};const response=editing?await dbClient.from('jobs').update(payload).eq('id',job().id).select().single():await dbClient.from('jobs').insert({...payload,user_id:user.id}).select().single();if(response.error)return dbError(response.error);data.currentJobId=response.data.id;await loadFromSupabase();notice(editing?'Đã lưu Job vào Supabase.':'Đã tạo Job trên Supabase.');go('workspace')};
$('#save-candidate').onclick=async()=>{const user=await requireDbUser();if(!user)return;const activeJob=job();if(!activeJob)return notice('Hãy tạo Job trước khi thêm ứng viên.');const name=$('#candidate-name').value.trim(),role=$('#candidate-role').value.trim(),cvText=$('#candidate-cv').value.trim(),file=$('#candidate-file').files[0],button=$('#save-candidate');if(!name||!role||(!cvText&&!file))return notice('Vui lòng nhập tên, vị trí và tải file hoặc nhập nội dung CV.');if(file&&file.size>5*1024*1024)return notice('File CV phải nhỏ hơn hoặc bằng 5 MB.');if(file&&!/\.(pdf|doc|docx)$/i.test(file.name))return notice('Chỉ hỗ trợ file PDF, DOC hoặc DOCX.');button.disabled=true;button.textContent=file?'Đang tải CV…':'Đang lưu…';let cvFilePath=null;if(file){const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');cvFilePath=`${user.id}/${crypto.randomUUID()}-${safeName}`;const {error:uploadError}=await dbClient.storage.from('candidate-cvs').upload(cvFilePath,file,{upsert:false,contentType:file.type});if(uploadError){button.disabled=false;button.textContent='Thêm ứng viên vào Job';return dbError(uploadError)}}const {data:newCandidate,error:candidateError}=await dbClient.from('candidates').insert({user_id:user.id,name,source:role,cv_text:cvText||null,cv_file_path:cvFilePath}).select().single();if(candidateError){if(cvFilePath)await dbClient.storage.from('candidate-cvs').remove([cvFilePath]);button.disabled=false;button.textContent='Thêm ứng viên vào Job';return dbError(candidateError)}const {error:applicationError}=await dbClient.from('applications').insert({job_id:activeJob.id,candidate_id:newCandidate.id,status:'new'});button.disabled=false;button.textContent='Thêm ứng viên vào Job';if(applicationError){if(cvFilePath)await dbClient.storage.from('candidate-cvs').remove([cvFilePath]);return dbError(applicationError)}await loadFromSupabase();currentCandidateId=newCandidate.id;renderDetail();notice(cvFilePath?'Đã tải CV và thêm ứng viên vào Supabase.':'Đã thêm ứng viên vào Supabase.');go('detail')};
$('#status-trigger').onclick=()=>{const menu=$('#status-menu'),current=candidate();menu.hidden=!menu.hidden;menu.innerHTML=statuses.map(status=>`<button data-status="${status}">${status===current.status?'✓ ':''}${status}</button>`).join('');menu.querySelectorAll('button').forEach(button=>button.onclick=async()=>{const next=button.dataset.status;if(next===current.status){menu.hidden=true;return}const from=dbStatus[current.status],to=dbStatus[next];const {error:updateError}=await dbClient.from('applications').update({status:to}).eq('id',current.applicationId);if(updateError)return dbError(updateError);const {error:historyError}=await dbClient.from('application_status_history').insert({application_id:current.applicationId,from_status:from,to_status:to});if(historyError)return dbError(historyError);current.status=next;menu.hidden=true;renderDetail();renderWorkspace();notice('Đã cập nhật trạng thái trên Supabase.')})};
$('#delete-candidate').onclick=async()=>{const current=candidate();if(!current)return;if(!window.confirm(`Xóa ứng viên “${current.name}”? Thao tác này không thể hoàn tác.`))return;const button=$('#delete-candidate');button.disabled=true;button.textContent='Đang xóa…';const {error}=await dbClient.from('candidates').delete().eq('id',current.id);button.disabled=false;button.textContent='Xóa ứng viên';if(error)return dbError(error);currentCandidateId=null;await loadFromSupabase();notice('Đã xóa ứng viên khỏi Supabase.');go('workspace')};
(async()=>{const {data:{user}}=await dbClient.auth.getUser();dbUser=user;if(dbUser){await loadFromSupabase();go('jobs')}else go('auth-login')})();
